alias gor='go run'
alias gorm='go run main.go'
alias gob='go build'
alias gobm='go build main.go'
alias gmd='go mod'
alias gord='go run .'
alias got='go test'
alias gota='h && go test ./... && cd - > /dev/null 2>&1'
alias gotav='h && go test -v ./... && cd - > /dev/null 2>&1'
alias gocov='go test -coverprofile=c.out && go tool cover -html=c.out && rm c.out'
