alias gor='go run'
alias gorm='go run main.go'
alias gob='go build'
alias gobm='go build main.go'
alias gmd='go mod'
alias gord='go run .'
alias got='go test'
alias gota='h && go test ./... && cd - > /dev/null'
