alias temprs='cargo init --name temprs'
alias c='cargo'
alias cr='cargo run'
alias cra='cargo run --'
alias ct='cargo nextest run'
alias rustc='/Users/diegofrias/.cargo/bin/rustc'
alias cdoc='cargo doc --open'
