#!/bin/zsh

cobra-cli $*

local comm=$1
case $comm in
  "init")
    mkdir pkg
    mv cmd pkg
    mkdir pkg/cmd/root
    mv pkg/cmd/root.go pkg/cmd/root
    mkdir -p cmd/${PWD:t}
    mv main.go cmd/${PWD:t}
    ;;
  "add")
    local sub=$2
    mkdir pkg/cmd/$sub
    mv cmd/$sub.go pkg/cmd/$sub
    ;;
esac
