#!/bin/zsh


# Get the name and size of every language in the repo, of the form "NAME\nSIZE"
local results=$(
gh repo view \
  --json 'languages' \
  --jq '.languages.[] | .node.name, .size'
)
# Split the results into an array by newlines
local data=(${(f)results})

local ordered_data
# Make an associative array
typeset -A ordered_data

local total=0
local i
for (( i=1; i<=${#data}; i++ )); do
  # If the index of the item is even, it will be a size, so add it to the total
  if (( i % 2 == 0 )); then
    local total=$((total + ${data[i]}))
  # Otherwise it's the name of the language
  else
    ordered_data[${data[i]}]=${data[i+1]}
  fi
done

local language
local size
for language size in ${(kv)ordered_data}; do
  # Gets percentage of total size of the language
  echo "$language: $((size*100/total))%"
# Sort by size
done | sort -k1.2
