#!/bin/zsh


local results=$(
gh repo view \
  --json 'languages' \
  --jq '.languages.[] | .node.name, .size'
)
local data=(${(f)results})

local ordered_data=
typeset -A ordered_data

local total=0
for (( i=1; i<=${#data}; i++ )); do
  if (( i % 2 == 0 )); then
    local total=$((total + ${data[i]}))
  else
    ordered_data[${data[i]}]=${data[i+1]}
  fi
done

local language=
local size=
for language size in ${(kv)ordered_data}; do
  echo "$language: $((size*100/total))%"
done | sort -k1.2
