#!/bin/zsh

# h goes upwards until reaching the root directory of the project

local start=$PWD

while [[ ! -f go.mod && ! -f go.sum && ! -f requirements.txt && $PWD != $HOME ]]; do
  cd ..
done
pwd

# For cleaner appearance on directory stack
pushd $start > /dev/null
cd - > /dev/null
