#!/bin/zsh

# h goes upwards until reaching the root directory of the project


local start=$PWD

while [[ $PWD != $HOME && ! -f LICENSE && ! -d .git && ! -f README.md ]]; do
  cd ..
done
pwd

# For cleaner appearance on directory stack
pushd $start > /dev/null
cd - > /dev/null
