#!/bin/zsh

# Counts the number of lines of all files in the current directory. If the
# -r or --recurse option is passed, recursively counts the lines of files


if [[ $# > 2 ]]; then
  echo 'Too many arguments'
  return 1
fi

if [[ -z $1 ]]; then
  wc -l *(.)
  return 0
fi

case $1 in
  '-r' | '--recurse')
    local pattern='**/'
    if [[ -n $2 ]]; then
      pattern+="*$2"
    fi
    local pattern+='*(.)'
    wc -l ${~pattern}
    ;;
  *)
    if [[ $2 == '-r' || $2 == '--recurse' ]]; then
      local pattern='**/'
    fi
    pattern+="*$1*(.)"
    wc -l ${~pattern}
esac

# Needed for weird behavior with +=
unset pattern
