#!/bin/zsh

# If user tries to edit a directory, first attempts to edit files of the form
# DIRNAME.* before exiting with an error. Additionally, if the user tries to
# edit a binary, try to edit a file matching the pattern FILE.* instead. If the
# user tries to edit a file with no extension, try to edit a file with any extension
# with the same name.


# Needed for the #q glob flag
setopt EXTENDED_GLOB

if [[ ${1:e} == '' && ! -d $1 ]]; then
  # Glob pattern for file to edit
  local new="$1.*"
  if [[ -n $~new(#qN) ]]; then
    command nvim $~new ${@[2,-1]}
    return 0
  else
    command nvim $1 ${@[2,-1]}
    return 0
  fi
fi

# Check if the first argument is a directory
if [[ -d $1 ]]; then
  local new="$1.*"
  # Check if the glob matches by checking the amount of matches
  if [[ -n $~new(#qN) ]]; then
    # Match the glob pattern
    local file=($~new)
    # Use command to non-recursively call neovim
    command nvim $file ${@[2,-1]}
  else
    echo "$1 is a directory!"
    return 1
  fi
else
  command nvim $@
fi
