#!/bin/zsh

# nvimm will open any matching main.* file in neovim


setopt EXTENDED_GLOB

if [[ $# != 0 ]]; then
  echo 'Usage: nvm'
  return 1
fi

readonly local PATTERN='main.*'

if [[ -z $~PATTERN(#qN) ]]; then
  echo 'No matches found'
  return 1
elif [[ $(ls $~PATTERN | wc -l) -gt 1 ]]; then
  echo 'More than one match found'
  return 1
fi

nvim $~PATTERN
