#!/bin/zsh

# Checks if the first argument is a directory
if [[ -d $1 ]]; then
  new="$1.*"
  # Matches the glob pattern
  file=(${~new})
  # Checks if the glob matches anything
  if [[ -f $file ]]; then
    # Uses command to non-recursively call neovim
    command nvim $file ${@[2,-1]}
  else
    echo "$1 is a directory!"
  fi
else
  command nvim $@
fi
