#!/bin/zsh

# nvimm will open any matching main.* file in neovim


setopt EXTENDED_GLOB

if [[ $# != 0 ]]; then
  echo 'Usage: nvm'
  return 1
fi

readonly local PATTERN='main.*'
# Get the amount of matches for the pattern
local match_amount=$PATTERN(#qN)

if [[ -z ${~match_amount} ]]; then
  echo 'No matches found'
  return 1
else if
  echo 'Found too many main files'
  return 1
fi

nvim ${~PATTERN}
