#!/bin/zsh

# Create requirements.txt, or remove it's contents if it exists
echo -n '' > requirements.txt

# Get all imports from .py files and turn it into an array
imports=("${(@f)$(rg '(?<=^import |^from )\b\w+\b' --pcre2 --only-matching --no-line-number --no-filename --glob '*.py' --ignore-file <(echo venv))}")
pip_freeze=$(pip freeze)


added=()
for module in $imports; do
    SEARCH="^\b$module\b" 
    # Check if module is not in the txt file of modules
    if [[ -z $(grep $SEARCH "$HOME/.dotfiles/zsh/autoload/resources/pipreq/std_lib.txt") ]]; then
        # Gets version from pip freeze
        version=$(echo $pip_freeze | grep $SEARCH)
        # Appends to requirements.txt
        echo $version >> requirements.txt
        echo "$version put in requirements.txt"
        added+=$module
    fi
done
