#!/bin/zsh

# Gets the imports from .py files and puts them into requirements.txt


case $1 in
  '-r' | '--requirements')
    local requirements=true
    ;;
  ?*)
    # Check if string has something in it
    echo 'Invalid arguments'
    return 1
    ;;
  *)
    local requirements=false
esac

# Needed for the qN flag
setopt EXTENDED_GLOB
# Check if any .py files exist anywhere in the directory
if [[ -z **/*.py(#qN) ]]; then
  echo 'No .py files found in current directory'
  return 1
fi
unsetopt EXTENDED_GLOB

# Get all imports from .py files and turn it into an array, ignores the venv dir
local imports=("${(@f)$(rg '(?<=^import |^from )\b\w+\b' --pcre2 --only-matching --no-line-number --no-filename --glob '*.py' --ignore-file <(echo venv))}")
local pip_freeze=$(pip freeze)

if ($requirements); then
  # Makes empty requirements.txt or clears it if it exists
  echo -n '' > requirements.txt
fi

local added=()
local module
for module in $imports; do
  local search="^\b$module\b" 
  # Check if module is not in the txt file of modules and if it isn't in $added
  if [[ -z $(grep $search "$HOME/.dotfiles/zsh/autoload/resources/piprq.txt") && ${added[(Ie)$module]} == 0 ]]; then
    # Gets version from pip freeze
    local version=$(echo $pip_freeze | grep $search)
    # Checks if string is empty (module not in pip freeze)
    if [[ -z $version ]]; then
      continue
    fi
    if ($requirements); then
      # Appends to requirements.txt
      echo $version >> requirements.txt
      echo "$version put in requirements.txt"
    else
      echo $version
    fi
    added+=$module
  fi
done

if [[ ${#added} == 0 ]]; then
  echo 'No external packages found'
fi
