#!/bin/zsh

if [[ $# != 1 ]]; then
  echo 'Usage: proj <project type>'
  return 1
fi

# Glob patterns match files starting with . too
setopt GLOB_DOTS
local available=(go vim)
local proj_name=${PWD:t}

if [[ ! " ${available[*]} " =~ " $1 " ]]; then
  echo 'Available types:'
  local proj_type
  for proj_type in $available; do
    echo "  $proj_type"
  done
  return 1
fi

case $1 in
  'go')
    go mod init github.com/dzfrias/$proj_name
esac

cp -R ~/.dotfiles/zsh/autoload/resources/proj/all/* .
# Copy everything recursively and overwrite clashing files
cp -Rf ~/.dotfiles/zsh/autoload/resources/proj/$1/* .

local -A exts
local file
for file in $(ls **/*(.)); do
  local ext=${file:e}
  exts[$ext]=1
done
for ext in ${(k)exts}; do
  fd 'PROJNAME\..+' -x mv {} {//}/$proj_name.$ext
done
fd 'PROJNAME' --type directory --exec mv {} {//}/$proj_name

# To get around gitignore
mv projections.json .projections.json

rplc "PROJNAME/$proj_name" **/*(.)
