#!/bin/zsh

# rclean cleans a git repository of the given arguments


# Clean repo of arguments and removes the last line to avoid confusion
bfg --replace-text <(echo $@) .git | sed '$d'
rm -r .git.bfg-report
# Push to GitHub
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push --force
