#!/bin/zsh

# Replaces text with the form 'OLD/NEW' (first argument) in files matching glob
# pattern (second argument)


if [[ $# < 2 ]]; then
  echo 'Usage: rplc OLD/NEW GLOB'
fi

# Replaces contents of files matching GLOB with a sed replace expression
ls ${@:2} | xargs sed -i '' "s/$1/g"
