#!/bin/zsh

# Opens the target directory's Xcode project no matter how nested it is in
# the directory.


if [[ $# != 1 ]]; then
  echo 'Need one argument'
  return 1
fi

# Checks if target is not a directory
if [[ ! -d $1 ]]; then
  echo 'Target needs to a be a directory'
  return 1
fi

setopt EXTENDED_GLOB

# Pattern for files in any subdirectories with the .xcodeproj extension
local xcodeproj_pattern="$1/**/*.xcodeproj"

# Checks if amount of matches of the glob pattern is zero
if [[ -z ${~xcodeproj_pattern}(#qN) ]]; then
  echo 'No xcode project found'
  return 1
fi

# Opens the file (will default to opening in Xcode)
open ${~xcodeproj_pattern}
