#!/bin/bash

# Use sudo without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Default layout
yabai -m config layout bsp

yabai -m config top_padding    5
yabai -m config bottom_padding 5
yabai -m config left_padding   5
yabai -m config right_padding  5
yabai -m config window_gap     5

# Only have window shadows for floating windows
yabai -m config window_shadow float

# 90% unfocused window opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Floating windows on top
yabai -m config window_topmost on

# When window is focused, mouse follows too
yabai -m config mouse_follows_focus on
