#!/bin/bash

# Use sudo without password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Default layout
yabai -m config layout bsp

yabai -m config top_padding    10
yabai -m config bottom_padding 6
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

# Only have window shadows for floating windows
yabai -m config window_shadow float

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xffc0caf5
yabai -m config normal_window_border_color 0xaac0caf5

# When window is focused, mouse follows too
yabai -m config mouse_follows_focus on

# Float these apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off

yabai -m config external_bar all:30:2
