# vim: set foldmethod=marker:


# {{{ EXPORTS
export EDITOR=nvim
# Highlights anything with main.* as purple to exa, and any directory as blue 
# and bold
export EXA_COLORS='di=34;1:main.*=35'
# Changes man pages to be viewed with bat
export MANPAGER='sh -c "col -bx | bat --language man --plain"'
export ZSH_PLUGINS_ALIAS_TIPS_EXCLUDES='gorm gor'
# Mail goes to ~/.mbox instead of ~/mbox, less home directory clutter
export MBOX="$HOME/.mbox"
export FZF_DEFAULT_COMMAND='fd --type file --hidden'
export FZF_DEFAULT_OPTS="\
  --preview-window=up \
  --prompt='~> ' \
  --color='pointer:#00FFFF,prompt:#0db9d7,bg+:#263c42,hl+:#c19eff,hl:#b38aff,info:#75bf7a,border:#4f4970' \
  --black \
  --bind='ctrl-f:preview-half-page-down,ctrl-b:preview-half-page-up'"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export PATH="$HOME/.cargo/bin:$PATH"
export RUST_LOG='trace'
# }}}


# {{{ SETUPS
export ZSH="$HOME/.oh-my-zsh"
plugins=(
  git
  zsh-autosuggestions
  zoxide
  ripgrep
  fd
  direnv
  web-search
  alias-tips
  autoupdate
  fzf
  almostontop
  pip
  copybuffer
  zsh-autopair
  zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh
eval "$(oh-my-posh --init --shell zsh --config ~/.dotfiles/zsh/theme.json)"
eval "$(zoxide init zsh --cmd j)"
# }}}


# {{{ OPTIONS
setopt NO_NOMATCH
setopt NOTIFY
# }}}


# {{{ BINDKEYS & ZLE
# Maps jk to normal mode in the zsh line editor
bindkey    jk      vi-cmd-mode
# Binds shift-tab to accept autosuggestions
bindkey    '^[[Z'  autosuggest-accept
# Clears the prompt, writes the text, and enters it
bindkey -s 'uu'    '^Uj ..^M'
bindkey -s '^E'    '^Uj ~/.dotfiles^M'

# Copies current prompt text to clipboard
bindkey -M viins '^Y' copybuffer
bindkey -M vicmd '^Y' copybuffer
bindkey -M emacs '^Y' copybuffer

function zle-keymap-select {
  # Change cursor for depending on the mode
  if [[ ${KEYMAP} == vicmd ]] || [[ $1 = 'block' ]]; then
    echo -ne '\e[2 q'
  elif [[ ${KEYMAP} == main ]] ||
    [[ ${KEYMAP} == viins ]] ||
    [[ ${KEYMAP} = '' ]] ||
    [[ $1 = 'beam' ]]; then
    echo -ne '\e[6 q'
  fi
}
zle -N zle-keymap-select
# }}}


# {{{ FUNCTIONS
source "$HOME/.dotfiles/zsh/functions.zsh"
# This script will load everything in the autload directory
source $HOME/.dotfiles/zsh/autoload.zsh
# }}}


# {{{ HIGHLIGHT STYLES
# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md
# for all possible highlight options
typeset -A ZSH_HIGHLIGHT_STYLES
# Modifiers like sudo and command
ZSH_HIGHLIGHT_STYLES[precommand]="fg=blue,underline"
# The main part of commands
ZSH_HIGHLIGHT_STYLES[arg0]="fg=cyan"
# Keywords like for and if (purple)
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#bb9af7'
# 'string', "string", and $"string"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=green'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=green'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=green'
# 'string and "string (red)
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#db4b4b'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#db4b4b'
# - options (dark cyan)
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#0db9d7'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#0db9d7'
# }}}


# {{{ MISC
() {
  readonly local CRON_FILE="$HOME/.dotfiles/setup/resources/crontab"
  # Modeline to set syntax
  echo "# vim:syntax=crontab\n" > $CRON_FILE
  # Puts crontab into cron.txt
  crontab -l >> $CRON_FILE
}

() {
  local file
  for file in ~/.dotfiles/zsh/aliases/*; do
    source $file
  done
}
# }}}
