tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jandedobbeleer/oh-my-posh"
# Companion library to apr, the Apache Portable Runtime library
brew "apr-util"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Development kit for the Java programming language
brew "openjdk"
# Remove large files or passwords from Git history like git-filter-branch
brew "bfg"
# Perl compatible regular expressions library
brew "pcre"
# Core application library for C
brew "glib"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Transport Layer Security (TLS) Library
brew "gnutls"
# GNU Emacs text editor
brew "emacs"
# Emacs dependency management
brew "cask"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Load/unload environment variables based on $PWD
brew "direnv"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Generate introspection data for GObject libraries
brew "gobject-introspection"
# OpenType text shaping engine
brew "harfbuzz"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Distributed revision control system
brew "git"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Platform built on V8 to build network applications
brew "node", link: false
# Swiss-army knife of markup format conversion
brew "pandoc"
# Interactive environments for writing and running code
brew "jupyterlab"
# Style and grammar checker
brew "languagetool"
# Next-gen compiler infrastructure
brew "llvm"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Prompt theme engine for any shell
brew "oh-my-posh"
# General-purpose scripting language
brew "php"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Feature-rich console based todo list manager
brew "task"
# Send macOS User Notifications from the command-line
brew "terminal-notifier"
# JavaScript package manager
brew "yarn"
# UNIX shell (command interpreter)
brew "zsh"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# Application launcher and productivity software
cask "alfred"
# Desktop client for GitHub repositories
cask "github"
# Web browser
cask "google-chrome"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Automation software
cask "keyboard-maestro"
# Team communication and collaboration software
cask "slack"
