tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Next-generation test runner for Rust
brew "cargo-nextest"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Simple terminal UI for git commands
brew "lazygit"
# Utility for directing compilation
brew "make"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
# Prompt theme engine for any shell
brew "oh-my-posh"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Terminal multiplexer
brew "tmux"
# Program that allows you to count code, quickly
brew "tokei"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Application launcher and productivity software
cask "alfred"
# Enable Windows-like alt-tab
cask "alt-tab"
# Developer targeted fonts with a high number of glyphs
cask "font-meslo-lg-nerd-font"
# Desktop automation application
cask "hammerspoon"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Run commands and display their output on the desktop
cask "ubersicht"
