tap "dart-lang/dart"
tap "dzfrias/formulae"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "konradsz/igrep", "https://github.com/konradsz/igrep.git"
tap "sass/sass"
tap "tinygo-org/tools"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Compiler infrastructure and toolchain library for WebAssembly
brew "binaryen"
# Glorious Glasgow Haskell Compilation System
brew "ghc"
# Command-line interface for Cabal and Hackage
brew "cabal-install"
# Perl compatible regular expressions library with a new API
brew "pcre2"
# Next-generation test runner for Rust
brew "cargo-nextest"
# Cross-platform make
brew "cmake"
# Platform built on V8 to build network applications
brew "node"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# LLVM bytecode to JavaScript compiler
brew "emscripten"
# C library implementing the SSH2 protocol
brew "libssh2"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Perfect hash function generator
brew "gperf"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Command-line benchmarking tool
brew "hyperfine"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Handy way to save and run project-specific commands
brew "just"
# Simple terminal UI for git commands
brew "lazygit"
# Bare libuv bindings for lua
brew "luv"
# Cross platform, open source .NET development framework
brew "mono"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Small build system for use with gyp or CMake
brew "ninja"
# Prompt theme engine for any shell
brew "oh-my-posh"
# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Safe, concurrent, practical language
brew "rust"
# Intuitive find & replace CLI
brew "sd"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Terminal multiplexer
brew "tmux"
# Program that allows you to count code, quickly
brew "tokei"
# Language for application scale JavaScript development
brew "typescript"
# Web Assembly Binary Toolkit
brew "wabt"
# Your favorite rust -> wasm workflow tool!
brew "wasm-pack"
# Standalone JIT-style runtime for WebAssembly, using Cranelift
brew "wasmtime"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Highly configurable TUI project manager
brew "dzfrias/formulae/projectable"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# Interactive Grep
brew "konradsz/igrep/igrep"
# Stylesheet Preprocessor
brew "sass/sass/sass"
# TinyGo is a Go compiler for small places. Microcontrollers, WebAssembly, and command-line tools. Based on LLVM.
brew "tinygo-org/tools/tinygo"
# GPU-accelerated terminal emulator
cask "alacritty"
# Application launcher and productivity software
cask "alfred"
# App to build and share containerized applications and microservices
cask "docker"
# Web browser
cask "firefox"
# Developer targeted fonts with a high number of glyphs
cask "font-meslo-lg-nerd-font"
# Web browser
cask "google-chrome"
# Desktop automation application
cask "hammerspoon"
# Windows manager and desktop organiser
cask "hazeover"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Browser for ambitious developers
cask "polypane"
# Run commands and display their output on the desktop
cask "ubersicht"
